variant_id: cray_O2_libsci_cpu
description: "Cray CCE, -O2, cray-libsci, CPU-only"

modules:
  # Compiler toolchain
  swap:
    - "PrgEnv-cray"
  load: []
  unload: []

compiler:
  cc: "cc"
  cxx: "CC"
  fc: "ftn"
  cflags: ["-O2"]
  cxxflags: ["-O2"]
  fcflags: ["-O2"]

libraries:
  blas: "cray-libsci"
  fftw: "cray-fftw"

gpu:
  enabled: false

build:
  # Customize these once you know your DFTB+ source + build system.
  cmake_args: []
  make_jobs: 16


