variant_id: gnu_O3_fftw_cpu
description: "GNU, -O3, FFTW, CPU-only"

modules:
  swap:
    - "PrgEnv-gnu"
  load:
    - "fftw"
  unload:
    - "cray-libsci"

compiler:
  cc: "cc"
  cxx: "CC"
  fc: "ftn"
  cflags: ["-O3"]
  cxxflags: ["-O3"]
  fcflags: ["-O3"]

libraries:
  blas: "cray-libsci"
  fftw: "fftw"

gpu:
  enabled: false

build:
  cmake_args: []
  make_jobs: 16


