variant_id: intel_O3_mkl_cpu
description: "Intel (PrgEnv-intel), -O3, MKL, CPU-only"

modules:
  swap:
    - "PrgEnv-intel"
  load:
    - "mkl"
  unload:
    - "cray-libsci"

compiler:
  cc: "cc"
  cxx: "CC"
  fc: "ftn"
  cflags: ["-O3"]
  cxxflags: ["-O3"]
  fcflags: ["-O3"]

libraries:
  blas: "mkl"
  fftw: "mkl"

gpu:
  enabled: false

build:
  cmake_args: []
  make_jobs: 16


