variant_id: nvhpc_O3_cuda_gpu
description: "NVHPC, -O3, CUDA enabled, GPU build"

modules:
  swap:
    - "PrgEnv-nvhpc"
  load:
    - "craype-accel-nvidia80"
  unload:
    - "cray-libsci"

compiler:
  cc: "cc"
  cxx: "CC"
  fc: "ftn"
  cflags: ["-O3"]
  cxxflags: ["-O3"]
  fcflags: ["-O3"]

libraries:
  blas: "none"
  fftw: "none"

gpu:
  enabled: true

build:
  cmake_args: []
  make_jobs: 16


