runset_id: gpu_basic
description: "GPU on/off comparison (basic) on GPU-capable nodes"

queue: normal
walltime: "01:00:00"
mem: "110gb"

cases:
  - run_id: n1_gpu1
    select: 1
    ncpus: 16
    mpiprocs: 1
    ompthreads: 16
    ngpus: 1

  - run_id: n1_gpu4
    select: 1
    ncpus: 64
    mpiprocs: 4
    ompthreads: 16
    ngpus: 4


